# Makefiles


MK_INCLUDE_DIR ?= hack/mk

MK_VARS_DIR ?= $(MK_INCLUDE_DIR)/vars
MK_VARS_FILE ?= $(MK_VARS_DIR)/main.mk
MK_VARS_PROJECT_TYPE_DIR ?= $(MK_VARS_DIR)/$(PROJECT_TYPE)
MK_VARS_PROJECT_TYPE_FILE ?= $(MK_VARS_PROJECT_TYPE_DIR)/main.mk
MK_VARS_PROJECT_FILE ?= $(MK_VARS_PROJECT_TYPE_DIR)/$(PROJECT_SHORTNAME).mk

MK_DIST_FILE ?= Makefile-dist.mk

MK_TARGETS_DIR ?= $(MK_INCLUDE_DIR)/targets
MK_TARGETS_FILE ?= $(MK_TARGETS_DIR)/main.mk
MK_TARGETS_PROJECT_TYPE_DIR ?= $(MK_TARGETS_DIR)/$(PROJECT_TYPE)
MK_TARGETS_PROJECT_TYPE_FILE ?= $(MK_TARGETS_PROJECT_TYPE_DIR)/main.mk
MK_TARGETS_PROJECT_FILE ?= $(MK_TARGETS_PROJECT_TYPE_DIR)/$(PROJECT_SHORTNAME).mk

MK_PIPELINES_DIR ?= $(MK_INCLUDE_DIR)/pipelines
MK_PIPELINES_FILE ?= $(MK_PIPELINES_DIR)/main.mk

include $(MK_VARS_FILE)

ifneq (,$(wildcard $(MK_DIST_FILE)))
include $(MK_DIST_FILE)
endif

include $(MK_TARGETS_FILE)

include $(MK_PIPELINES_FILE)
